services:

  mongodb:
    image: mongo:6
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  airflow:
    build:
      context: .
      dockerfile: Dockerfile.airflow
    container_name: airflow
    restart: always
    depends_on:
      - mongodb
    ports:
      - "8080:8080"

    environment:
      - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
      - AIRFLOW__API_AUTH__JWT_SECRET=mysecretkey123
      - AIRFLOW__API__AUTH_BACKENDS=airflow.api.auth.backend.basic_auth
      - AIRFLOW__WEBSERVER__AUTHENTICATE=True
      - AIRFLOW__WEBSERVER__RBAC=True
      - _AIRFLOW_WWW_USER_USERNAME=admin
      - _AIRFLOW_WWW_USER_PASSWORD=admin

      # 🔥 IMPORTANT FIX
      - MONGO_URI=mongodb://mongodb:27017/

    volumes:
      - .:/opt/airflow

    command: airflow standalone

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    container_name: dashboard
    depends_on:
      - mongodb
    volumes:
      - .:/app
    ports:
      - "8501:8501"

    environment:
      - MONGO_URI=mongodb://mongodb:27017/

    command: streamlit run dashboard/app.py --server.port 8501 --server.address 0.0.0.0

volumes:
  mongo_data: